---
title: "intersecteR"
output: rmarkdown::html_vignette
vignette: >
    %\VignetteIndexEntry{intersecteR}
    %\VignetteEngine{knitr::rmarkdown}
    %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(tidyverse)
library(intersecteR)
data(marker_set)
tidy_sets(marker_set, 'set')
tidy_sets(marker_set, 'element')
```

```{r}
intersects <- intrscts(marker_set, max = 3)
intersects
intersects <- intrscts(marker_set, min = 2, max = 2)
intersects
tidy_intrscts(intersects)
```

```{r}
g <- marker_set %>%
    '['(lengths(.) >= 3) %>% 
    intrscts(min_rank = 2, max_rank = 2) %>%
    tidy_intrscts(fisher = TRUE) %>% 
    embed()

p <- g %E>% 
    filter(p.value <= 0.0001, estimate > 2) %N>% 
    mutate(degree = igraph::degree(.)) %N>% 
    filter(degree > 0) %N>% 
    left_join(
        USairports %>% 
            as_tbl_graph() %>% 
            activate('nodes') %>% 
            as_tibble()
    ) %N>% 
    left_join(
        as_tibble(.) %>% separate(col = City, into = c(NA, 'State'), sep = ', ')
    ) %E>% 
    mutate(estimate = ifelse(is.infinite(estimate), 11, estimate)) %E>% 
    ggraph(layout = 'fr', weights = ratio) + 
    ggraph::geom_edge_link() + 
    ggraph::geom_node_point(aes(col = State)) + 
    ggraph::geom_node_text(nudge_y = 0.2, nudge_x = 0.2, aes(label = name), size = 2) + 
    scale_colour_viridis_d()
```
